;; TODO:
;;   * 次のように書き換えたい
;;   (add-to-list 'auto-mode-alist '("\\.rb\\'" . enh-ruby-mode))
;;   * 可能なら他のモード専用の設定ファイルに拡張子の設定を分散させる
(setq auto-mode-alist
      (append (list
                '("\\.html$"  . html-mode)
                '("\\.htm$"   . html-mode)
                '("\.el$"     . emacs-lisp-mode)
                '("\.emacs$"  . emacs-lisp-mode)
                '("\\.tex$"   . yatex-mode)
                '("\\.sh$"    . shell-script-mode)
                '("\\.sql$"   . sql-mode)
                '("\\.txt$"   . text-mode)
                '("\\.diff$"  . diff-mode)
                '("\\.patch$" . diff-mode)
                '("[Mm]akefile$" . makefile-mode)
                '("Makefile.am$" . makefile-mode)
                '("Makefile.in$" . makefile-mode)
                '("\\.erl$"      . erlang-mode)
                '("\\.erl.in$"   . erlang-mode)
                '("\\.erl.orig$" . erlang-mode)
                '("\\.hrl$"      . erlang-mode)
                '("\\.hrl.in$"   . erlang-mode)
                '("\\.hrl.orig$" . erlang-mode)
                ;; '("\\.js$"   . javascript-mode)
                '("\\.js$"   . js2-mode)
                '("\\.json$" . javascript-mode)
                '("\\.xml$"   . nxml-mode)
                '("\\.conf$"   . conf-space-mode)
                '("\\.vhost$"   . conf-space-mode)
                ;; Markdown
                '("\\.md$"   . markdown-mode)
                '("\\.py$"    . python-mode)
                '("\\.py.in$" . python-mode)
                '("\\.yml$" . yaml-mode)
                '("\\.rst$" . rst-mode)
                '("\\.rest$" . rst-mode)
                auto-mode-alist)
              )
      )
